### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [edyounis/qfast-sc#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary qfast-sc -w /tmp/ext qfast-sc==1.0.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting qfast-sc==1.0.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/f90/8b766295da19a/qfast-sc-1.0.1.tar.gz (3.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  WARNING: Missing build requirements in pyproject.toml for qfast-sc==1.0.1 from http://10.10.0.139:9191/root/pypi/%2Bf/f90/8b766295da19a/qfast-sc-1.0.1.tar.gz#sha256=f908b766295da19a2d7e736c1699e798cc0d3c9be062141e650ab85efafdbb0d.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 /tmp/tmpaemv0oqw get_requires_for_build_wheel /tmp/tmp64_md4rg
       cwd: /tmp/pip-wheel-nn65pzod/qfast-sc
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/tmp/tmpaemv0oqw", line 280, in <module>
      main()
    File "/tmp/tmpaemv0oqw", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpaemv0oqw", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5szszymw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-5szszymw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5szszymw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 249, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5szszymw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 15, in <module>
      with open( req_path ) as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-nn65pzod/qfast-sc/requirements.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/venv/bin/python3 /tmp/tmpaemv0oqw get_requires_for_build_wheel /tmp/tmp64_md4rg Check the logs for full command output.
```

**Comment by thatch** [comment]
I sent a PR but can't test further because of it needing a missing version of tensorflow
